(Issue #13) Try testing with MPICH

diff --git a/.github/workflows/test_bfrescoxpro_sdist.yml b/.github/workflows/test_bfrescoxpro_sdist.yml
--- a/.github/workflows/test_bfrescoxpro_sdist.yml
+++ b/.github/workflows/test_bfrescoxpro_sdist.yml
@@ -11,11 +11,6 @@ jobs:
   #####----- FULL TESTING WITHOUT COVERAGE
   # Prefer full end-to-end test using package installed on demand from source
   # distribution rather than testing in local clone alone or with a tox task.
-  #
-  # This also verifies a procedure provided in the documentation.
-  #
-  # TODO: Add in test with MPICH eventually when either Meson is fixed or a
-  # proper workaround should be tested.
   test_openmpi_installation:
     strategy:
       matrix:
@@ -70,6 +65,68 @@ jobs:
         pushd $BFRESCOXPRO_PATH
         python -m build --sdist
         python -m pip install -v dist/bfrescoxpro-*.tar.gz
+        popd
+        # Log info
+        echo ""
+        which python
+        python -m pip list
+        # Run tests through package
+        echo ""
+        python -c "import bfrescoxpro ; exit(not bfrescoxpro.test())"
+
+  # We presently need to build with MPICH using a workaround (Issue #17).  Once
+  # this is resolved, this job should be merged into the job above.
+  test_mpich_installation:
+    strategy:
+      matrix:
+        os: [ubuntu-24.04]
+        mpi_impl: ["mpich"]
+        python-version: ["3.13"]
+    runs-on: ${{ matrix.os }}
+    steps:
+    - uses: actions/checkout@v4
+
+    - name: Install compiler suite
+      run: |
+        if [ "${{ runner.os }}" = "macOS" ]; then
+           HOMEBREW_BIN_PATH=$(brew --prefix gcc)/bin
+           echo "$HOMEBREW_BIN_PATH" >> $GITHUB_PATH
+        fi
+
+    - name: Install ${{ matrix.mpi_impl }}
+      run: |
+        if   [ "${{ runner.os }}" = "Linux" ]; then
+           sudo apt-get update
+           if [ "${{ matrix.mpi_impl }}" = "mpich" ]; then
+              sudo apt-get -y install mpich libmpich-dev
+           else
+              echo "Cannot install ${{ matrix.mpi_impl }} for Linux"
+              exit 1
+           fi
+        elif [ "${{ runner.os }}" = "macOS" ]; then
+           brew update
+           if [ "${{ matrix.mpi_impl }}" = "mpich" ]; then
+              brew install mpich
+           else
+              echo "Cannot install ${{ matrix.mpi_impl }} for macOS"
+              exit 1
+           fi
+        fi
+
+    - name: Set up Python ${{ matrix.python-version }}
+      uses: actions/setup-python@v5
+      with:
+        python-version: ${{ matrix.python-version }}
+
+    - name: Build, install, & test bfrescoxpro
+      run: |
+        echo ""
+        python -m pip install --upgrade pip
+        python -m pip install build
+        # Build source distribution & install
+        pushd $BFRESCOXPRO_PATH
+        python -m build --sdist
+        BFRESCOX_USE_MPI=enabled python -m pip install -v dist/bfrescoxpro-*.tar.gz
         popd
         # Log info
         echo ""
